/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'music' : null } |
  { 'other' : null } |
  { 'vlog' : null } |
  { 'education' : null } |
  { 'gaming' : null } |
  { 'comedy' : null };
export interface Channel {
  'id' : ChannelId,
  'principal' : Principal,
  'name' : string,
  'profile' : string,
}
export type ChannelId = string;
export interface ChannelStripeConnection {
  'channelId' : ChannelId,
  'stripeAccountId' : string,
}
export interface Comment {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'videoId' : VideoId,
}
export interface Course {
  'id' : string,
  'title' : string,
  'channelId' : ChannelId,
  'requiredTierLevel' : [] | [bigint],
  'description' : string,
  'courseImage' : [] | [string],
  'isVisible' : boolean,
  'priceUsd' : [] | [bigint],
  'videoIds' : Array<VideoId>,
}
export interface Donation {
  'id' : string,
  'channelId' : ChannelId,
  'message' : [] | [string],
  'timestamp' : Time,
  'amountUsd' : bigint,
  'donor' : Principal,
}
export interface MembershipTier {
  'id' : string,
  'tierLevel' : bigint,
  'channelId' : ChannelId,
  'name' : string,
  'description' : string,
  'priceUsd' : bigint,
}
export interface Playlist {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'description' : string,
  'visibility' : PlaylistVisibility,
  'videoIds' : Array<VideoId>,
}
export type PlaylistVisibility = { 'privateVisibility' : null } |
  { 'publicVisibility' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeAccount {
  'id' : string,
  'owner' : Principal,
  'payoutSettings' : [] | [string],
  'secretKey' : string,
  'accountName' : string,
  'connectId' : [] | [string],
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscription {
  'id' : string,
  'status' : SubscriptionStatus,
  'nextBillingDate' : Time,
  'tierId' : string,
  'channelId' : ChannelId,
  'user' : Principal,
  'startDate' : Time,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'canceled' : null } |
  { 'past_due' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VideoId = string;
export interface VideoMetadata {
  'id' : VideoId,
  'title' : string,
  'likeCount' : bigint,
  'thumbnailUrl' : string,
  'channelId' : ChannelId,
  'requiredTierLevel' : [] | [bigint],
  'description' : string,
  'viewCount' : bigint,
  'isPrivate' : boolean,
  'category' : Category,
  'videoUrl' : string,
  'uploadDate' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[Comment], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelSubscription' : ActorMethod<[string], undefined>,
  'connectChannelToStripeAccount' : ActorMethod<
    [ChannelStripeConnection],
    undefined
  >,
  'createChannel' : ActorMethod<[Channel], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCourse' : ActorMethod<[Course], undefined>,
  'createMembershipTier' : ActorMethod<[MembershipTier], undefined>,
  'createPlaylist' : ActorMethod<[Playlist], undefined>,
  'createStripeAccount' : ActorMethod<[StripeAccount], undefined>,
  'createSubscription' : ActorMethod<[Subscription], undefined>,
  'deleteCourse' : ActorMethod<[string], undefined>,
  'deleteMembershipTier' : ActorMethod<[string], undefined>,
  'deletePlaylist' : ActorMethod<[string], undefined>,
  'deleteStripeAccount' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[VideoId], undefined>,
  'followChannel' : ActorMethod<[ChannelId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannel' : ActorMethod<[ChannelId], [] | [Channel]>,
  'getChannelCourses' : ActorMethod<[ChannelId], Array<Course>>,
  'getChannelDonations' : ActorMethod<[ChannelId], Array<Donation>>,
  'getChannelFollowers' : ActorMethod<[ChannelId], Array<Principal>>,
  'getChannelMembershipTiers' : ActorMethod<[ChannelId], Array<MembershipTier>>,
  'getChannelStripeConnection' : ActorMethod<
    [ChannelId],
    [] | [ChannelStripeConnection]
  >,
  'getChannelVideos' : ActorMethod<[ChannelId], Array<VideoMetadata>>,
  'getComments' : ActorMethod<[VideoId], Array<Comment>>,
  'getCourse' : ActorMethod<[string], [] | [Course]>,
  'getFollowedChannels' : ActorMethod<[], Array<ChannelId>>,
  'getFullVideoMetadata' : ActorMethod<
    [VideoId],
    [] | [{ 'video' : VideoMetadata, 'channel' : Channel }]
  >,
  'getPersonalizedCourses' : ActorMethod<[], Array<Course>>,
  'getPlaylist' : ActorMethod<[string], [] | [Playlist]>,
  'getPublicPlaylists' : ActorMethod<[], Array<Playlist>>,
  'getStripeAccount' : ActorMethod<[string], [] | [StripeAccount]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getThumbnailUrl' : ActorMethod<[VideoId], [] | [string]>,
  'getUserChannels' : ActorMethod<[], Array<Channel>>,
  'getUserDonationHistory' : ActorMethod<[], Array<Donation>>,
  'getUserPlaylists' : ActorMethod<[], Array<Playlist>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStripeAccounts' : ActorMethod<[], Array<StripeAccount>>,
  'getUserSubscriptionTierLevel' : ActorMethod<[ChannelId], [] | [bigint]>,
  'getVideo' : ActorMethod<[VideoId], [] | [VideoMetadata]>,
  'getVideoAuthenticated' : ActorMethod<[VideoId], [] | [VideoMetadata]>,
  'getVideoUrl' : ActorMethod<[VideoId], [] | [string]>,
  'getVideosByCategory' : ActorMethod<[Category], Array<VideoMetadata>>,
  'hasActiveSubscription' : ActorMethod<[ChannelId], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowingChannel' : ActorMethod<[ChannelId], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'likeVideo' : ActorMethod<[VideoId], undefined>,
  'recordDonation' : ActorMethod<[Donation], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchVideos' : ActorMethod<[string], Array<VideoMetadata>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'toggleVideoPrivacy' : ActorMethod<[VideoId], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unfollowChannel' : ActorMethod<[ChannelId], undefined>,
  'updateCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateChannel' : ActorMethod<[ChannelId, string, string], undefined>,
  'updateCourse' : ActorMethod<[string, Course], undefined>,
  'updateMembershipTier' : ActorMethod<[string, MembershipTier], undefined>,
  'updatePlaylist' : ActorMethod<[string, Playlist], undefined>,
  'updateStripeAccount' : ActorMethod<[string, StripeAccount], undefined>,
  'updateVideo' : ActorMethod<[VideoId, VideoMetadata], undefined>,
  'uploadVideo' : ActorMethod<[VideoMetadata], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];