/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const VideoId = IDL.Text;
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'videoId' : VideoId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChannelId = IDL.Text;
export const ChannelStripeConnection = IDL.Record({
  'channelId' : ChannelId,
  'stripeAccountId' : IDL.Text,
});
export const Channel = IDL.Record({
  'id' : ChannelId,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'profile' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'channelId' : ChannelId,
  'requiredTierLevel' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'courseImage' : IDL.Opt(IDL.Text),
  'isVisible' : IDL.Bool,
  'priceUsd' : IDL.Opt(IDL.Nat),
  'videoIds' : IDL.Vec(VideoId),
});
export const MembershipTier = IDL.Record({
  'id' : IDL.Text,
  'tierLevel' : IDL.Nat,
  'channelId' : ChannelId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'priceUsd' : IDL.Nat,
});
export const PlaylistVisibility = IDL.Variant({
  'privateVisibility' : IDL.Null,
  'publicVisibility' : IDL.Null,
});
export const Playlist = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'description' : IDL.Text,
  'visibility' : PlaylistVisibility,
  'videoIds' : IDL.Vec(VideoId),
});
export const StripeAccount = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'payoutSettings' : IDL.Opt(IDL.Text),
  'secretKey' : IDL.Text,
  'accountName' : IDL.Text,
  'connectId' : IDL.Opt(IDL.Text),
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'canceled' : IDL.Null,
  'past_due' : IDL.Null,
});
export const Subscription = IDL.Record({
  'id' : IDL.Text,
  'status' : SubscriptionStatus,
  'nextBillingDate' : Time,
  'tierId' : IDL.Text,
  'channelId' : ChannelId,
  'user' : IDL.Principal,
  'startDate' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Donation = IDL.Record({
  'id' : IDL.Text,
  'channelId' : ChannelId,
  'message' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'amountUsd' : IDL.Nat,
  'donor' : IDL.Principal,
});
export const Category = IDL.Variant({
  'music' : IDL.Null,
  'other' : IDL.Null,
  'vlog' : IDL.Null,
  'education' : IDL.Null,
  'gaming' : IDL.Null,
  'comedy' : IDL.Null,
});
export const VideoMetadata = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'channelId' : ChannelId,
  'requiredTierLevel' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'isPrivate' : IDL.Bool,
  'category' : Category,
  'videoUrl' : IDL.Text,
  'uploadDate' : Time,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addComment' : IDL.Func([Comment], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelSubscription' : IDL.Func([IDL.Text], [], []),
  'connectChannelToStripeAccount' : IDL.Func([ChannelStripeConnection], [], []),
  'createChannel' : IDL.Func([Channel], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCourse' : IDL.Func([Course], [], []),
  'createMembershipTier' : IDL.Func([MembershipTier], [], []),
  'createPlaylist' : IDL.Func([Playlist], [], []),
  'createStripeAccount' : IDL.Func([StripeAccount], [], []),
  'createSubscription' : IDL.Func([Subscription], [], []),
  'deleteCourse' : IDL.Func([IDL.Text], [], []),
  'deleteMembershipTier' : IDL.Func([IDL.Text], [], []),
  'deletePlaylist' : IDL.Func([IDL.Text], [], []),
  'deleteStripeAccount' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([VideoId], [], []),
  'followChannel' : IDL.Func([ChannelId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannel' : IDL.Func([ChannelId], [IDL.Opt(Channel)], ['query']),
  'getChannelCourses' : IDL.Func([ChannelId], [IDL.Vec(Course)], ['query']),
  'getChannelDonations' : IDL.Func([ChannelId], [IDL.Vec(Donation)], ['query']),
  'getChannelFollowers' : IDL.Func(
      [ChannelId],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getChannelMembershipTiers' : IDL.Func(
      [ChannelId],
      [IDL.Vec(MembershipTier)],
      ['query'],
    ),
  'getChannelStripeConnection' : IDL.Func(
      [ChannelId],
      [IDL.Opt(ChannelStripeConnection)],
      ['query'],
    ),
  'getChannelVideos' : IDL.Func(
      [ChannelId],
      [IDL.Vec(VideoMetadata)],
      ['query'],
    ),
  'getComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
  'getFollowedChannels' : IDL.Func([], [IDL.Vec(ChannelId)], ['query']),
  'getFullVideoMetadata' : IDL.Func(
      [VideoId],
      [IDL.Opt(IDL.Record({ 'video' : VideoMetadata, 'channel' : Channel }))],
      ['query'],
    ),
  'getPersonalizedCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getPlaylist' : IDL.Func([IDL.Text], [IDL.Opt(Playlist)], ['query']),
  'getPublicPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
  'getStripeAccount' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StripeAccount)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getThumbnailUrl' : IDL.Func([VideoId], [IDL.Opt(IDL.Text)], ['query']),
  'getUserChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getUserDonationHistory' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getUserPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStripeAccounts' : IDL.Func([], [IDL.Vec(StripeAccount)], ['query']),
  'getUserSubscriptionTierLevel' : IDL.Func(
      [ChannelId],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getVideo' : IDL.Func([VideoId], [IDL.Opt(VideoMetadata)], ['query']),
  'getVideoAuthenticated' : IDL.Func(
      [VideoId],
      [IDL.Opt(VideoMetadata)],
      ['query'],
    ),
  'getVideoUrl' : IDL.Func([VideoId], [IDL.Opt(IDL.Text)], ['query']),
  'getVideosByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(VideoMetadata)],
      ['query'],
    ),
  'hasActiveSubscription' : IDL.Func([ChannelId], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowingChannel' : IDL.Func([ChannelId], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([VideoId], [], []),
  'recordDonation' : IDL.Func([Donation], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoMetadata)], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleVideoPrivacy' : IDL.Func([VideoId], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unfollowChannel' : IDL.Func([ChannelId], [], []),
  'updateCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChannel' : IDL.Func([ChannelId, IDL.Text, IDL.Text], [], []),
  'updateCourse' : IDL.Func([IDL.Text, Course], [], []),
  'updateMembershipTier' : IDL.Func([IDL.Text, MembershipTier], [], []),
  'updatePlaylist' : IDL.Func([IDL.Text, Playlist], [], []),
  'updateStripeAccount' : IDL.Func([IDL.Text, StripeAccount], [], []),
  'updateVideo' : IDL.Func([VideoId, VideoMetadata], [], []),
  'uploadVideo' : IDL.Func([VideoMetadata], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const VideoId = IDL.Text;
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'videoId' : VideoId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChannelId = IDL.Text;
  const ChannelStripeConnection = IDL.Record({
    'channelId' : ChannelId,
    'stripeAccountId' : IDL.Text,
  });
  const Channel = IDL.Record({
    'id' : ChannelId,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'profile' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'channelId' : ChannelId,
    'requiredTierLevel' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'courseImage' : IDL.Opt(IDL.Text),
    'isVisible' : IDL.Bool,
    'priceUsd' : IDL.Opt(IDL.Nat),
    'videoIds' : IDL.Vec(VideoId),
  });
  const MembershipTier = IDL.Record({
    'id' : IDL.Text,
    'tierLevel' : IDL.Nat,
    'channelId' : ChannelId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'priceUsd' : IDL.Nat,
  });
  const PlaylistVisibility = IDL.Variant({
    'privateVisibility' : IDL.Null,
    'publicVisibility' : IDL.Null,
  });
  const Playlist = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'description' : IDL.Text,
    'visibility' : PlaylistVisibility,
    'videoIds' : IDL.Vec(VideoId),
  });
  const StripeAccount = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'payoutSettings' : IDL.Opt(IDL.Text),
    'secretKey' : IDL.Text,
    'accountName' : IDL.Text,
    'connectId' : IDL.Opt(IDL.Text),
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'canceled' : IDL.Null,
    'past_due' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'id' : IDL.Text,
    'status' : SubscriptionStatus,
    'nextBillingDate' : Time,
    'tierId' : IDL.Text,
    'channelId' : ChannelId,
    'user' : IDL.Principal,
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Donation = IDL.Record({
    'id' : IDL.Text,
    'channelId' : ChannelId,
    'message' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'amountUsd' : IDL.Nat,
    'donor' : IDL.Principal,
  });
  const Category = IDL.Variant({
    'music' : IDL.Null,
    'other' : IDL.Null,
    'vlog' : IDL.Null,
    'education' : IDL.Null,
    'gaming' : IDL.Null,
    'comedy' : IDL.Null,
  });
  const VideoMetadata = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'channelId' : ChannelId,
    'requiredTierLevel' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'isPrivate' : IDL.Bool,
    'category' : Category,
    'videoUrl' : IDL.Text,
    'uploadDate' : Time,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addComment' : IDL.Func([Comment], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelSubscription' : IDL.Func([IDL.Text], [], []),
    'connectChannelToStripeAccount' : IDL.Func(
        [ChannelStripeConnection],
        [],
        [],
      ),
    'createChannel' : IDL.Func([Channel], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCourse' : IDL.Func([Course], [], []),
    'createMembershipTier' : IDL.Func([MembershipTier], [], []),
    'createPlaylist' : IDL.Func([Playlist], [], []),
    'createStripeAccount' : IDL.Func([StripeAccount], [], []),
    'createSubscription' : IDL.Func([Subscription], [], []),
    'deleteCourse' : IDL.Func([IDL.Text], [], []),
    'deleteMembershipTier' : IDL.Func([IDL.Text], [], []),
    'deletePlaylist' : IDL.Func([IDL.Text], [], []),
    'deleteStripeAccount' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([VideoId], [], []),
    'followChannel' : IDL.Func([ChannelId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannel' : IDL.Func([ChannelId], [IDL.Opt(Channel)], ['query']),
    'getChannelCourses' : IDL.Func([ChannelId], [IDL.Vec(Course)], ['query']),
    'getChannelDonations' : IDL.Func(
        [ChannelId],
        [IDL.Vec(Donation)],
        ['query'],
      ),
    'getChannelFollowers' : IDL.Func(
        [ChannelId],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getChannelMembershipTiers' : IDL.Func(
        [ChannelId],
        [IDL.Vec(MembershipTier)],
        ['query'],
      ),
    'getChannelStripeConnection' : IDL.Func(
        [ChannelId],
        [IDL.Opt(ChannelStripeConnection)],
        ['query'],
      ),
    'getChannelVideos' : IDL.Func(
        [ChannelId],
        [IDL.Vec(VideoMetadata)],
        ['query'],
      ),
    'getComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], ['query']),
    'getFollowedChannels' : IDL.Func([], [IDL.Vec(ChannelId)], ['query']),
    'getFullVideoMetadata' : IDL.Func(
        [VideoId],
        [IDL.Opt(IDL.Record({ 'video' : VideoMetadata, 'channel' : Channel }))],
        ['query'],
      ),
    'getPersonalizedCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getPlaylist' : IDL.Func([IDL.Text], [IDL.Opt(Playlist)], ['query']),
    'getPublicPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
    'getStripeAccount' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StripeAccount)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getThumbnailUrl' : IDL.Func([VideoId], [IDL.Opt(IDL.Text)], ['query']),
    'getUserChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getUserDonationHistory' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getUserPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStripeAccounts' : IDL.Func([], [IDL.Vec(StripeAccount)], ['query']),
    'getUserSubscriptionTierLevel' : IDL.Func(
        [ChannelId],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getVideo' : IDL.Func([VideoId], [IDL.Opt(VideoMetadata)], ['query']),
    'getVideoAuthenticated' : IDL.Func(
        [VideoId],
        [IDL.Opt(VideoMetadata)],
        ['query'],
      ),
    'getVideoUrl' : IDL.Func([VideoId], [IDL.Opt(IDL.Text)], ['query']),
    'getVideosByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(VideoMetadata)],
        ['query'],
      ),
    'hasActiveSubscription' : IDL.Func([ChannelId], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowingChannel' : IDL.Func([ChannelId], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([VideoId], [], []),
    'recordDonation' : IDL.Func([Donation], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoMetadata)], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleVideoPrivacy' : IDL.Func([VideoId], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unfollowChannel' : IDL.Func([ChannelId], [], []),
    'updateCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChannel' : IDL.Func([ChannelId, IDL.Text, IDL.Text], [], []),
    'updateCourse' : IDL.Func([IDL.Text, Course], [], []),
    'updateMembershipTier' : IDL.Func([IDL.Text, MembershipTier], [], []),
    'updatePlaylist' : IDL.Func([IDL.Text, Playlist], [], []),
    'updateStripeAccount' : IDL.Func([IDL.Text, StripeAccount], [], []),
    'updateVideo' : IDL.Func([VideoId, VideoMetadata], [], []),
    'uploadVideo' : IDL.Func([VideoMetadata], [], []),
  });
};

export const init = ({ IDL }) => { return []; };