/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Course {
    id: string;
    title: string;
    channelId: ChannelId;
    requiredTierLevel?: bigint;
    description: string;
    courseImage?: string;
    isVisible: boolean;
    priceUsd?: bigint;
    videoIds: Array<VideoId>;
}
export interface Subscription {
    id: string;
    status: SubscriptionStatus;
    nextBillingDate: Time;
    tierId: string;
    channelId: ChannelId;
    user: Principal;
    startDate: Time;
}
export interface Donation {
    id: string;
    channelId: ChannelId;
    message?: string;
    timestamp: Time;
    amountUsd: bigint;
    donor: Principal;
}
export interface StripeAccount {
    id: string;
    owner: Principal;
    payoutSettings?: string;
    secretKey: string;
    accountName: string;
    connectId?: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type VideoId = string;
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface MembershipTier {
    id: string;
    tierLevel: bigint;
    channelId: ChannelId;
    name: string;
    description: string;
    priceUsd: bigint;
}
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Comment {
    id: string;
    content: string;
    author: Principal;
    timestamp: Time;
    videoId: VideoId;
}
export type ChannelId = string;
export interface Playlist {
    id: string;
    title: string;
    creator: Principal;
    description: string;
    visibility: PlaylistVisibility;
    videoIds: Array<VideoId>;
}
export interface Channel {
    id: ChannelId;
    principal: Principal;
    name: string;
    profile: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface VideoMetadata {
    id: VideoId;
    title: string;
    likeCount: bigint;
    thumbnailUrl: string;
    channelId: ChannelId;
    requiredTierLevel?: bigint;
    description: string;
    viewCount: bigint;
    isPrivate: boolean;
    category: Category;
    videoUrl: string;
    uploadDate: Time;
}
export interface ChannelStripeConnection {
    channelId: ChannelId;
    stripeAccountId: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Category {
    music = "music",
    other = "other",
    vlog = "vlog",
    education = "education",
    gaming = "gaming",
    comedy = "comedy"
}
export enum PlaylistVisibility {
    privateVisibility = "privateVisibility",
    publicVisibility = "publicVisibility"
}
export enum SubscriptionStatus {
    active = "active",
    canceled = "canceled",
    past_due = "past_due"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addComment(comment: Comment): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelSubscription(subscriptionId: string): Promise<void>;
    connectChannelToStripeAccount(connection: ChannelStripeConnection): Promise<void>;
    createChannel(channel: Channel): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createCourse(course: Course): Promise<void>;
    createMembershipTier(tier: MembershipTier): Promise<void>;
    createPlaylist(playlist: Playlist): Promise<void>;
    createStripeAccount(account: StripeAccount): Promise<void>;
    createSubscription(subscription: Subscription): Promise<void>;
    deleteCourse(courseId: string): Promise<void>;
    deleteMembershipTier(tierId: string): Promise<void>;
    deletePlaylist(playlistId: string): Promise<void>;
    deleteStripeAccount(accountId: string): Promise<void>;
    deleteVideo(videoId: VideoId): Promise<void>;
    followChannel(channelId: ChannelId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChannel(channelId: ChannelId): Promise<Channel | null>;
    getChannelCourses(channelId: ChannelId): Promise<Array<Course>>;
    getChannelDonations(channelId: ChannelId): Promise<Array<Donation>>;
    getChannelFollowers(channelId: ChannelId): Promise<Array<Principal>>;
    getChannelMembershipTiers(channelId: ChannelId): Promise<Array<MembershipTier>>;
    getChannelStripeConnection(channelId: ChannelId): Promise<ChannelStripeConnection | null>;
    getChannelVideos(channelId: ChannelId): Promise<Array<VideoMetadata>>;
    getComments(videoId: VideoId): Promise<Array<Comment>>;
    getCourse(courseId: string): Promise<Course | null>;
    getFollowedChannels(): Promise<Array<ChannelId>>;
    getFullVideoMetadata(videoId: VideoId): Promise<{
        video: VideoMetadata;
        channel: Channel;
    } | null>;
    getPersonalizedCourses(): Promise<Array<Course>>;
    getPlaylist(playlistId: string): Promise<Playlist | null>;
    getPublicPlaylists(): Promise<Array<Playlist>>;
    getStripeAccount(accountId: string): Promise<StripeAccount | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getThumbnailUrl(videoId: VideoId): Promise<string | null>;
    getUserChannels(): Promise<Array<Channel>>;
    getUserDonationHistory(): Promise<Array<Donation>>;
    getUserPlaylists(): Promise<Array<Playlist>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStripeAccounts(): Promise<Array<StripeAccount>>;
    getUserSubscriptionTierLevel(channelId: ChannelId): Promise<bigint | null>;
    getVideo(videoId: VideoId): Promise<VideoMetadata | null>;
    getVideoAuthenticated(videoId: VideoId): Promise<VideoMetadata | null>;
    getVideoUrl(videoId: VideoId): Promise<string | null>;
    getVideosByCategory(category: Category): Promise<Array<VideoMetadata>>;
    hasActiveSubscription(channelId: ChannelId): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isFollowingChannel(channelId: ChannelId): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    likeVideo(videoId: VideoId): Promise<void>;
    recordDonation(donation: Donation): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchVideos(searchTerm: string): Promise<Array<VideoMetadata>>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    toggleVideoPrivacy(videoId: VideoId): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unfollowChannel(channelId: ChannelId): Promise<void>;
    updateCallerUserProfile(updatedProfile: UserProfile): Promise<void>;
    updateChannel(channelId: ChannelId, updatedName: string, updatedProfile: string): Promise<void>;
    updateCourse(courseId: string, updatedCourse: Course): Promise<void>;
    updateMembershipTier(tierId: string, updatedTier: MembershipTier): Promise<void>;
    updatePlaylist(playlistId: string, updatedPlaylist: Playlist): Promise<void>;
    updateStripeAccount(accountId: string, updatedAccount: StripeAccount): Promise<void>;
    updateVideo(videoId: VideoId, updatedMetadata: VideoMetadata): Promise<void>;
    uploadVideo(metadata: VideoMetadata): Promise<void>;
}
import type { Category as _Category, Channel as _Channel, ChannelId as _ChannelId, ChannelStripeConnection as _ChannelStripeConnection, Course as _Course, Donation as _Donation, Playlist as _Playlist, PlaylistVisibility as _PlaylistVisibility, StripeAccount as _StripeAccount, StripeSessionStatus as _StripeSessionStatus, Subscription as _Subscription, SubscriptionStatus as _SubscriptionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VideoId as _VideoId, VideoMetadata as _VideoMetadata, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addComment(arg0: Comment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelSubscription(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelSubscription(arg0);
            return result;
        }
    }
    async connectChannelToStripeAccount(arg0: ChannelStripeConnection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.connectChannelToStripeAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectChannelToStripeAccount(arg0);
            return result;
        }
    }
    async createChannel(arg0: Channel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createChannel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChannel(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createCourse(arg0: Course): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(to_candid_Course_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(to_candid_Course_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createMembershipTier(arg0: MembershipTier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMembershipTier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMembershipTier(arg0);
            return result;
        }
    }
    async createPlaylist(arg0: Playlist): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlaylist(to_candid_Playlist_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlaylist(to_candid_Playlist_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createStripeAccount(arg0: StripeAccount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStripeAccount(to_candid_StripeAccount_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStripeAccount(to_candid_StripeAccount_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSubscription(arg0: Subscription): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscription(to_candid_Subscription_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscription(to_candid_Subscription_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCourse(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return result;
        }
    }
    async deleteMembershipTier(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMembershipTier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMembershipTier(arg0);
            return result;
        }
    }
    async deletePlaylist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlaylist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlaylist(arg0);
            return result;
        }
    }
    async deleteStripeAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStripeAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStripeAccount(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async followChannel(arg0: ChannelId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followChannel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followChannel(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannel(arg0: ChannelId): Promise<Channel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannel(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannel(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannelCourses(arg0: ChannelId): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelCourses(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelCourses(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannelDonations(arg0: ChannelId): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelDonations(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelDonations(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannelFollowers(arg0: ChannelId): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelFollowers(arg0);
            return result;
        }
    }
    async getChannelMembershipTiers(arg0: ChannelId): Promise<Array<MembershipTier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelMembershipTiers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelMembershipTiers(arg0);
            return result;
        }
    }
    async getChannelStripeConnection(arg0: ChannelId): Promise<ChannelStripeConnection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelStripeConnection(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelStripeConnection(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannelVideos(arg0: ChannelId): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelVideos(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelVideos(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComments(arg0: VideoId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getCourse(arg0: string): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowedChannels(): Promise<Array<ChannelId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowedChannels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowedChannels();
            return result;
        }
    }
    async getFullVideoMetadata(arg0: VideoId): Promise<{
        video: VideoMetadata;
        channel: Channel;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFullVideoMetadata(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFullVideoMetadata(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPersonalizedCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalizedCourses();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalizedCourses();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlaylist(arg0: string): Promise<Playlist | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaylist(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaylist(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicPlaylists(): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicPlaylists();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicPlaylists();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeAccount(arg0: string): Promise<StripeAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeAccount(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeAccount(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getThumbnailUrl(arg0: VideoId): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getThumbnailUrl(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThumbnailUrl(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserChannels(): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserChannels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserChannels();
            return result;
        }
    }
    async getUserDonationHistory(): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDonationHistory();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDonationHistory();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPlaylists(): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPlaylists();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPlaylists();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStripeAccounts(): Promise<Array<StripeAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStripeAccounts();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStripeAccounts();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSubscriptionTierLevel(arg0: ChannelId): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSubscriptionTierLevel(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSubscriptionTierLevel(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideo(arg0: VideoId): Promise<VideoMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoAuthenticated(arg0: VideoId): Promise<VideoMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoAuthenticated(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoAuthenticated(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoUrl(arg0: VideoId): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoUrl(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoUrl(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByCategory(arg0: Category): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByCategory(to_candid_Category_n56(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByCategory(to_candid_Category_n56(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasActiveSubscription(arg0: ChannelId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasActiveSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasActiveSubscription(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFollowingChannel(arg0: ChannelId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowingChannel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowingChannel(arg0);
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async likeVideo(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeVideo(arg0);
            return result;
        }
    }
    async recordDonation(arg0: Donation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDonation(to_candid_Donation_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDonation(to_candid_Donation_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchVideos(arg0: string): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchVideos(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchVideos(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async toggleVideoPrivacy(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleVideoPrivacy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleVideoPrivacy(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unfollowChannel(arg0: ChannelId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowChannel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowChannel(arg0);
            return result;
        }
    }
    async updateCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerUserProfile(arg0);
            return result;
        }
    }
    async updateChannel(arg0: ChannelId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChannel(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChannel(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCourse(arg0: string, arg1: Course): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, to_candid_Course_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, to_candid_Course_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMembershipTier(arg0: string, arg1: MembershipTier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipTier(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipTier(arg0, arg1);
            return result;
        }
    }
    async updatePlaylist(arg0: string, arg1: Playlist): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlaylist(arg0, to_candid_Playlist_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlaylist(arg0, to_candid_Playlist_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStripeAccount(arg0: string, arg1: StripeAccount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStripeAccount(arg0, to_candid_StripeAccount_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStripeAccount(arg0, to_candid_StripeAccount_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVideo(arg0: VideoId, arg1: VideoMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideo(arg0, to_candid_VideoMetadata_n60(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideo(arg0, to_candid_VideoMetadata_n60(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadVideo(arg0: VideoMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideo(to_candid_VideoMetadata_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideo(to_candid_VideoMetadata_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Category_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Course_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Donation_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donation): Donation {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PlaylistVisibility_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlaylistVisibility): PlaylistVisibility {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Playlist_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Playlist): Playlist {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_StripeAccount_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeAccount): StripeAccount {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_VideoMetadata_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoMetadata): VideoMetadata {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Channel]): Channel | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChannelStripeConnection]): ChannelStripeConnection | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : from_candid_Course_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        video: _VideoMetadata;
        channel: _Channel;
    }]): {
    video: VideoMetadata;
    channel: Channel;
} | null {
    return value.length === 0 ? null : from_candid_record_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Playlist]): Playlist | null {
    return value.length === 0 ? null : from_candid_Playlist_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StripeAccount]): StripeAccount | null {
    return value.length === 0 ? null : from_candid_StripeAccount_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoMetadata]): VideoMetadata | null {
    return value.length === 0 ? null : from_candid_VideoMetadata_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    channelId: _ChannelId;
    requiredTierLevel: [] | [bigint];
    description: string;
    courseImage: [] | [string];
    isVisible: boolean;
    priceUsd: [] | [bigint];
    videoIds: Array<_VideoId>;
}): {
    id: string;
    title: string;
    channelId: ChannelId;
    requiredTierLevel?: bigint;
    description: string;
    courseImage?: string;
    isVisible: boolean;
    priceUsd?: bigint;
    videoIds: Array<VideoId>;
} {
    return {
        id: value.id,
        title: value.title,
        channelId: value.channelId,
        requiredTierLevel: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.requiredTierLevel)),
        description: value.description,
        courseImage: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.courseImage)),
        isVisible: value.isVisible,
        priceUsd: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.priceUsd)),
        videoIds: value.videoIds
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    channelId: _ChannelId;
    message: [] | [string];
    timestamp: _Time;
    amountUsd: bigint;
    donor: Principal;
}): {
    id: string;
    channelId: ChannelId;
    message?: string;
    timestamp: Time;
    amountUsd: bigint;
    donor: Principal;
} {
    return {
        id: value.id,
        channelId: value.channelId,
        message: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.message)),
        timestamp: value.timestamp,
        amountUsd: value.amountUsd,
        donor: value.donor
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    title: string;
    likeCount: bigint;
    thumbnailUrl: string;
    channelId: _ChannelId;
    requiredTierLevel: [] | [bigint];
    description: string;
    viewCount: bigint;
    isPrivate: boolean;
    category: _Category;
    videoUrl: string;
    uploadDate: _Time;
}): {
    id: VideoId;
    title: string;
    likeCount: bigint;
    thumbnailUrl: string;
    channelId: ChannelId;
    requiredTierLevel?: bigint;
    description: string;
    viewCount: bigint;
    isPrivate: boolean;
    category: Category;
    videoUrl: string;
    uploadDate: Time;
} {
    return {
        id: value.id,
        title: value.title,
        likeCount: value.likeCount,
        thumbnailUrl: value.thumbnailUrl,
        channelId: value.channelId,
        requiredTierLevel: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.requiredTierLevel)),
        description: value.description,
        viewCount: value.viewCount,
        isPrivate: value.isPrivate,
        category: from_candid_Category_n37(_uploadFile, _downloadFile, value.category),
        videoUrl: value.videoUrl,
        uploadDate: value.uploadDate
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: _VideoMetadata;
    channel: _Channel;
}): {
    video: VideoMetadata;
    channel: Channel;
} {
    return {
        video: from_candid_VideoMetadata_n35(_uploadFile, _downloadFile, value.video),
        channel: value.channel
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    creator: Principal;
    description: string;
    visibility: _PlaylistVisibility;
    videoIds: Array<_VideoId>;
}): {
    id: string;
    title: string;
    creator: Principal;
    description: string;
    visibility: PlaylistVisibility;
    videoIds: Array<VideoId>;
} {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        description: value.description,
        visibility: from_candid_PlaylistVisibility_n45(_uploadFile, _downloadFile, value.visibility),
        videoIds: value.videoIds
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    payoutSettings: [] | [string];
    secretKey: string;
    accountName: string;
    connectId: [] | [string];
}): {
    id: string;
    owner: Principal;
    payoutSettings?: string;
    secretKey: string;
    accountName: string;
    connectId?: string;
} {
    return {
        id: value.id,
        owner: value.owner,
        payoutSettings: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.payoutSettings)),
        secretKey: value.secretKey,
        accountName: value.accountName,
        connectId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.connectId))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    music: null;
} | {
    other: null;
} | {
    vlog: null;
} | {
    education: null;
} | {
    gaming: null;
} | {
    comedy: null;
}): Category {
    return "music" in value ? Category.music : "other" in value ? Category.other : "vlog" in value ? Category.vlog : "education" in value ? Category.education : "gaming" in value ? Category.gaming : "comedy" in value ? Category.comedy : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    privateVisibility: null;
} | {
    publicVisibility: null;
}): PlaylistVisibility {
    return "privateVisibility" in value ? PlaylistVisibility.privateVisibility : "publicVisibility" in value ? PlaylistVisibility.publicVisibility : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n53(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Array<Course> {
    return value.map((x)=>from_candid_Course_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donation>): Array<Donation> {
    return value.map((x)=>from_candid_Donation_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoMetadata>): Array<VideoMetadata> {
    return value.map((x)=>from_candid_VideoMetadata_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Playlist>): Array<Playlist> {
    return value.map((x)=>from_candid_Playlist_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StripeAccount>): Array<StripeAccount> {
    return value.map((x)=>from_candid_StripeAccount_n49(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_Course_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Course): _Course {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Donation_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Donation): _Donation {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_PlaylistVisibility_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaylistVisibility): _PlaylistVisibility {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Playlist_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Playlist): _Playlist {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_StripeAccount_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StripeAccount): _StripeAccount {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Subscription_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subscription): _Subscription {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_VideoMetadata_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoMetadata): _VideoMetadata {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    channelId: ChannelId;
    requiredTierLevel?: bigint;
    description: string;
    courseImage?: string;
    isVisible: boolean;
    priceUsd?: bigint;
    videoIds: Array<VideoId>;
}): {
    id: string;
    title: string;
    channelId: _ChannelId;
    requiredTierLevel: [] | [bigint];
    description: string;
    courseImage: [] | [string];
    isVisible: boolean;
    priceUsd: [] | [bigint];
    videoIds: Array<_VideoId>;
} {
    return {
        id: value.id,
        title: value.title,
        channelId: value.channelId,
        requiredTierLevel: value.requiredTierLevel ? candid_some(value.requiredTierLevel) : candid_none(),
        description: value.description,
        courseImage: value.courseImage ? candid_some(value.courseImage) : candid_none(),
        isVisible: value.isVisible,
        priceUsd: value.priceUsd ? candid_some(value.priceUsd) : candid_none(),
        videoIds: value.videoIds
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    creator: Principal;
    description: string;
    visibility: PlaylistVisibility;
    videoIds: Array<VideoId>;
}): {
    id: string;
    title: string;
    creator: Principal;
    description: string;
    visibility: _PlaylistVisibility;
    videoIds: Array<_VideoId>;
} {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        description: value.description,
        visibility: to_candid_PlaylistVisibility_n14(_uploadFile, _downloadFile, value.visibility),
        videoIds: value.videoIds
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    payoutSettings?: string;
    secretKey: string;
    accountName: string;
    connectId?: string;
}): {
    id: string;
    owner: Principal;
    payoutSettings: [] | [string];
    secretKey: string;
    accountName: string;
    connectId: [] | [string];
} {
    return {
        id: value.id,
        owner: value.owner,
        payoutSettings: value.payoutSettings ? candid_some(value.payoutSettings) : candid_none(),
        secretKey: value.secretKey,
        accountName: value.accountName,
        connectId: value.connectId ? candid_some(value.connectId) : candid_none()
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: SubscriptionStatus;
    nextBillingDate: Time;
    tierId: string;
    channelId: ChannelId;
    user: Principal;
    startDate: Time;
}): {
    id: string;
    status: _SubscriptionStatus;
    nextBillingDate: _Time;
    tierId: string;
    channelId: _ChannelId;
    user: Principal;
    startDate: _Time;
} {
    return {
        id: value.id,
        status: to_candid_SubscriptionStatus_n20(_uploadFile, _downloadFile, value.status),
        nextBillingDate: value.nextBillingDate,
        tierId: value.tierId,
        channelId: value.channelId,
        user: value.user,
        startDate: value.startDate
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    channelId: ChannelId;
    message?: string;
    timestamp: Time;
    amountUsd: bigint;
    donor: Principal;
}): {
    id: string;
    channelId: _ChannelId;
    message: [] | [string];
    timestamp: _Time;
    amountUsd: bigint;
    donor: Principal;
} {
    return {
        id: value.id,
        channelId: value.channelId,
        message: value.message ? candid_some(value.message) : candid_none(),
        timestamp: value.timestamp,
        amountUsd: value.amountUsd,
        donor: value.donor
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: VideoId;
    title: string;
    likeCount: bigint;
    thumbnailUrl: string;
    channelId: ChannelId;
    requiredTierLevel?: bigint;
    description: string;
    viewCount: bigint;
    isPrivate: boolean;
    category: Category;
    videoUrl: string;
    uploadDate: Time;
}): {
    id: _VideoId;
    title: string;
    likeCount: bigint;
    thumbnailUrl: string;
    channelId: _ChannelId;
    requiredTierLevel: [] | [bigint];
    description: string;
    viewCount: bigint;
    isPrivate: boolean;
    category: _Category;
    videoUrl: string;
    uploadDate: _Time;
} {
    return {
        id: value.id,
        title: value.title,
        likeCount: value.likeCount,
        thumbnailUrl: value.thumbnailUrl,
        channelId: value.channelId,
        requiredTierLevel: value.requiredTierLevel ? candid_some(value.requiredTierLevel) : candid_none(),
        description: value.description,
        viewCount: value.viewCount,
        isPrivate: value.isPrivate,
        category: to_candid_Category_n56(_uploadFile, _downloadFile, value.category),
        videoUrl: value.videoUrl,
        uploadDate: value.uploadDate
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaylistVisibility): {
    privateVisibility: null;
} | {
    publicVisibility: null;
} {
    return value == PlaylistVisibility.privateVisibility ? {
        privateVisibility: null
    } : value == PlaylistVisibility.publicVisibility ? {
        publicVisibility: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    active: null;
} | {
    canceled: null;
} | {
    past_due: null;
} {
    return value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.canceled ? {
        canceled: null
    } : value == SubscriptionStatus.past_due ? {
        past_due: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    music: null;
} | {
    other: null;
} | {
    vlog: null;
} | {
    education: null;
} | {
    gaming: null;
} | {
    comedy: null;
} {
    return value == Category.music ? {
        music: null
    } : value == Category.other ? {
        other: null
    } : value == Category.vlog ? {
        vlog: null
    } : value == Category.education ? {
        education: null
    } : value == Category.gaming ? {
        gaming: null
    } : value == Category.comedy ? {
        comedy: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
